name: Maven Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up JDK 11
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Test with Maven
      run: mvn clean test
      working-directory: my-app

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: packaged-artifacts
        path: target/**