name: Maven Build

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up JDK 11
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Get and set my-app version
      run: |
        version=${{vars.MY_APP_VERSION}}

        IFS='.' read -ra VERSION_PARTS <<< "$version"
        VERSION_PARTS[2]=$((VERSION_PARTS[2] + 1))
        new_version="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"
        echo "new_version=$new_version" >> $GITHUB_ENV
      
    - name: Test with Maven
      run: | 
        mvn versions:set -DnewVersion=${{env.new_version}}
        mvn clean test
      working-directory: my-app

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: packaged-artifacts
        path: my-app/target/**

    - name: Update version in my-app
      run: |
        gh variable set MY_APP_VERSION --body "${{env.new_version}}"
      env:
        GH_TOKEN: ${{ secrets.PAT }}

  publish-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout pages repo
      uses: actions/checkout@v4
      with:
        repository: devopselvis/java-example-with-jacoco-and-tests-test-results
        token: ${{ secrets.PAT }} 


    - name: Download production artifacts
      uses: actions/download-artifact@v4.1.4
      with:
        name: packaged-artifacts
        path: temp

    - name: delete me
      run: |
        pwd 
        ls -la


